fix basic function of hidden_channels.js
joe27g/EnhancedDiscord pull request #149
Opened 2020-11-12 10:16 UTC by xirreal

2020-12-08 16:34 UTC, xirreal commented
More fixes

2020-12-08 18:46 UTC, Xazii commented
I can't install ED, help me pls: discord id: @! Xazi#6666 
![Desktop Screenshot 2020 12 08 - 12 37 01 64 (2)](https://user-images.githubusercontent.com/75694915/101527307-1c6d5a80-398e-11eb-81f7-78d9f2d9d006.png)

2020-12-09 22:23 UTC, rauenzi requested changes

2020-12-09 22:23 UTC, rauenzi commented on plugins/avatar_links.js
> +        const reactData = theMenu[Object.keys(theMenu)[0]];
It is not guaranteed to be the first key, this is not a reliable solution. This is more reliable:

```
theMenu[Object.keys(theMenu).find(key => key.startsWith("__reactInternalInstance") || key.startsWith("__reactFiber"))]
```

2020-12-10 08:57 UTC, rauenzi approved these changes
LGTM

2020-12-10 23:06 UTC, merged